mytmux

diff --git a/bin/init-gpg-agent b/bin/init-gpg-agent
--- a/bin/init-gpg-agent
+++ b/bin/init-gpg-agent
@@ -7,4 +7,4 @@ export GPG_AGENT_INFO=${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent
 export SSH_AUTH_SOCK=${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent.ssh
 
 echo UPDATESTARTUPTTY | gpg-connect-agent >/dev/null 2>&1
-[ $? != 0 ] && warn "Initialization of gpg-agent failed." || msg "Initialized gpg-agent."
+[ $? != 0 ] && warn "Initialization of gpg-agent failed." || msg "gpg-agent initialized."
